openai:
  model: "gpt-3.5-turbo"
  api_key: ${OPENAI_API_KEY}  
  temperature: 0.3
  max_tokens: 2000

together:
  model: "meta-llama/Llama-2-7b-chat-hf"
  api_key: ${TOGETHER_API_KEY}
  temperature: 0.3
  max_tokens: 2000

openai_tests:
  model: "gpt-3.5-turbo"
  api_key: ${OPENAI_API_KEY}
  temperature: 0.4
  max_tokens: 2000

openrouter:
  api_key: ${OPENROUTER_API_KEY}
  model: "tngtech/deepseek-r1t2-chimera:free"
  max_tokens: 3000
  temperature: 0.7
